### ISSUE TITLE
Fer que quan un mail te una part de reply, l'esborri abans d'afegir el ticket

### ISSUE THREAD

**Issue by jaumemoral** [UPC/mailtoticket#1]

**Comment by jaumemoral** [comment]
Podem fer una primera versio en que quan hi ha un reply esborri el que hi ha entre blockquote sempre que nomes hi hagi un a primer nivell. Aixi evitem esborrar inlines.

**Comment by alexm** [comment]
Una altra opció interessant seria que gn6 amagui automàticament els
blockquotes que apareguin al final de tot, com fa gmail.
El dia 24/09/2015 09:44, "Jaume Moral" <notifications@github.com> va
escriure:

**Comment by alexm** [comment]
Veig una dificultat important a descobrir si els comentaris adjunts al correu són part de la conversa anterior del tiquet o són d'una conversa diferent, per exemple si es tracta d'un reenviament d'una altra conversa. Això és especialment important en els tiquets nous.

**Comment by jaumemoral** [comment]
La idea seria que els ticket nous no esborren res. Els reply esborren la
part citada en cas que nomes hi hagi una.
El dia 17/12/2015 13.39, "Alex Muntada" <notifications@github.com> va
escriure:

**Comment by jaumemoral** [comment]
Per ara aixo ja ho tenim fet. Tanco
