### ISSUE TITLE
L'script "check-qa.sh" falla si no està instal·lat pep8

### ISSUE THREAD

**Issue by aaguilera** [UPC/mailtoticket#105]
No sé si val la pena afegir `pep8` al `requirements.txt`, o si hem de considerar que `check-qa.sh` és una utilitat orientada als desenvolupadors, i que per tant `pep8` no és estrictament un requeriment de MailToTicket.

**Comment by alexm** [comment]
Efectivament no vaig posar el `pep8` ni el `radon` als requisits perquè només ho són per als desenvolupadors que ho vulguin. Configurar el pre-commit és opcional i per tant, també instal·lar-ne els requisits.

Una altra cosa és si hem de fer que el pre-commit no falli i no faci res si no troba algun dels seus requisits, però jo no ho consideraria un bug. En aquest cas és intencionat.

**Comment by jaumemoral** [comment]
Jo tampoc ho considero un error. Com a molt posaria als comentaris del script que cal com a requeriment.

Jo faig servir windows aixi que ni ho puc executar... i no ho considero un fallo

**Comment by aaguilera** [comment]
OK. El tanco com a invàlid, si us sembla.

**Comment by alexm** [comment]
Enlloc de dir que és invàlid ho classificaria com a millora.

**Comment by alexm** [comment]
Espero que així us agradi més ;-)

**Comment by alexm** [comment]
@jaumemoral sobre el suport per a Windows, no tinc ni idea de com va però suposo que es podria fer un `pre-commit.bat` equivalent.
