### ISSUE TITLE
La detecció del número de tiquet falla si el prefix té accents

### ISSUE THREAD

**Issue by alexm** [UPC/mailtoticket#114]
La instància de l'ATIC posa com a prefix `Avís tiquet NNN` i si es posa com a `regex_reply` el valor `.*?R[eEvV]:.*?Av.s tiquet ([\d]+)` falla.

**Comment by alexm** [comment]
Com a mesura temporal he proposat que utilitzin `.*?R[eEvV]:.*?s tiquet ([\d]+)` ja que he comprovat amb un petit _snippet_ que funciona encara que hi hagi accents, però caldria veure si es pot fer d'alguna manera més robusta pel cas que hi hagi accents.

**Comment by jaumemoral** [comment]
Es raro que la regex falli, no? De totes formes no veig problema en tenir una menys precisa, no crec que tinguem problemes de falsos positius.

Jo no faria res al respecte. Per solucionar aquests problemes la idea bona es fer-ho amb el message-id

**Comment by alexm** [comment]
Es veu que es menja els caràcters no ASCII i el _Subject_ acaba sent `Re: Avs tiquet ...`. Per això la regex no casa.

No és exactament un problema i per això l'he marcat com una millora i l'he deixat com a idea de futur.

**Comment by alexm** [comment]
De totes formes, als logs passa exactament el mateix, segurament perquè no es llegeix correctament alguns camps codificats en UTF-8.

**Comment by nuriarc02** [comment]
No se si us pot ajudar, però a Prisma també tenim "Avís tiquet NNN" com a UPCnet..fem servir gairebé la mateixa plantilla i funciona bé, no Jaume?

**Comment by aaguilera** [comment]
Comentari de prova (ara li hauria d'arribar a la Núria).

**Comment by jaumemoral** [comment]
Hola!

Doncs a Prisma i a Comunicació tinc una versió molt light de l'expressió, segurament degut a que també em vaig trobar aquest problema. Només busco "Re" i numero

".*?R[eE]:.*?([\d]+)"

Com que després el numero ha de coincidir amb un ticket obert... tampoc es generen falsos positius.

De totes formes, @alexm mirant el codi he vist que es fa l'expressió regular directament amb la versió ASCII del subject eliminant qualsevol caràcter no reconegut. Segurament seria una cosa a refactoritzar perque tingui més sentit. Quan ho vaig fer no tenia massa clar com solucionar temes d'encoding i vaig optar per la solució més radical. Seria questio de fer proves amb get_subject() en comptes de get_subject_ascii()

```
           subject = self.msg.get_subject_ascii()
            logger.info("Buscant numero a  %s" % subject)
            regex_reply = settings.get("regex_reply")
            p = re.compile(regex_reply)
            m = p.match(subject)
```

**Comment by alexm** [comment]
:+1:

En tot cas, potser sí que caldria documentar el comportament agressiu del filtrat de caràcters no ASCII al comentari corresponent del fitxer de configuració d'exemple i al manual.

**Comment by aaguilera** [comment]
Sembla que l'encoding del subject té una mica de "chicha". Jo he trobat això:

http://ncona.com/2011/06/using-utf-8-characters-on-an-e-mail-subject/

http://ginstrom.com/scribbles/2007/11/19/parsing-multilingual-email-with-python/

Mirant el nostre codi, dedueixo que la decodificació del "subject" es fa a al mètode `tracta_subject` de `mailticket.py`, però no sé veure perquè pot fallar en aquest cas concret. Caldria disposar de tests per a aquest mètode. Per altra banda, el problema potser no està en aquest mètode, sinó a la comprovació del propi "matching" amb la regexp (se m'acudeix que hi pot haver alguna peculiaritat de les regexp en Python i s'hagi d'indicar l'encoding d'alguna manera...).

**Comment by alexm** [comment]
Un problema relacionat és que tampoc es detecta bé el número de tiquet en el cas de `Subject: Re: =?utf-8?b?QXbDrXM=?= tiquet 12345: ...` (vegeu l'osticket 23). Miro de fer proves.

**Comment by alexm** [comment]
He fet un PR al repo privat amb un test per a cada part d'aquest problema.
