### ISSUE TITLE
Parsejar correctament *totes* les capçaleres que poden contenir adreces de correu

### ISSUE THREAD

**Issue by aaguilera** [UPC/mailtoticket#126]
El mètode `get_header()` de la classe `MailTicket` tracta de manera especial les capçaleres que contenen adreces de correu. Actualment, té en compte 'From', 'Resent-From', 'Reply-To', 'Resent-To', però caldria que contemplés també les capçaleres 'To' i 'Cc', ja que també contenen adreces de correu.

**Comment by jaumemoral** [comment]
Ep, aixo ja està fet

https://github.com/UPC/mailtoticket/pull/127

I mes que enhancement, jo ho considero un bug. Pero vaja, que ja està fet que es lo important
