### ISSUE TITLE
Passar a la nova API rest de identitat digital

### ISSUE THREAD

**Issue by jaumemoral** [UPC/mailtoticket#188]
Identitat digital ha canviat totalment la API i ja no va via SOA sino via rest amb una api key. S'hauria de reescriure el servei "identitat.py" per utilitzar aquesta nova API i afegir el parametre amb la clau al settings

**Comment by alexm** [comment]
Tenim data de caducitat per l'antic servei SOA? Ens pot ser útil per prioritzar adequadament.

**Comment by jaumemoral** [comment]
Realment ja ho tinc implementat al meu repo i en producció. Vull passar tots els canvis al repo oficial i he creat les issues per organitzar i fer les pull requests.

On dimarts, maig 28, 2019 11:19 CEST, Alex Muntada <notifications@github.com> wrote:
 
Tenim data de caducitat per l'antic servei SOA? Ens pot ser útil per prioritzar adequadament.

**Comment by alexm** [comment]
Està molt bé que ja no tinguis implementat :+1:

Suposo que hauríem d'escriure una guia de migració per la gent que tingui instàncies del MailToTicket corrent perquè hauran de demanar credencials noves, etc. Alguna idea de com fer-ho? En un fitxer de _change log_ o un _release notes_?

**Comment by jaumemoral** [comment]
Doncs jo crec que hauriem de posar versió al que tenim actualment i fer una nova release en la que canviaria clarament la versió i un fitxer explicant els canvis. Aixo tant per aquesta issue com la de passar a Python3, que son canvis importants que trenquen la compatibilitat cap enrera

**Comment by alexm** [comment]
Podríem utilitzar els _releases_ del propi github, oi? Així els usuaris també es podrien descarregar la versió que vulguin en tar.gz o zip sense necessitat del git.

**Comment by jaumemoral** [comment]
Tinc una pull requests amb els canvis necessaris #194 , pero ara mateix no me l'accepta perque tenim la opció tiquismiquis=true al travis. Falta revisar el codi per fer-lo més net

**Comment by aaguilera** [comment]
La Iolanda Garcia ha contactat amb nosaltres per avisar-nos del canvi en el sistema d'Identitat Digital. Ja li he dit que properament estarà fet el canvi. M'apunto avisar-la quan mailtoticket ja no depengui de la API antiga d'Identitat digital (suposo que, igual que ens ha avisat a nosaltres, ella deu haver avisat a la resta de subscriptors a la API, i per tant a la resta d'usuaris de mailtoticket).

**Comment by jaumemoral** [comment]
Si, si, per aixo vaig fer un "intent" de pujar el meu codi per tothom que ho necessités. Si algú vol agafar la branca i netejar-la una mica perque passis testos, perfecte. Jo no se si m'hi podré posar.

**Comment by aaguilera** [comment]
Fet. Ja passa els tests.

**Comment by alexm** [comment]
Veig que el canvi de #194 elimina el suport de SOA i el substitueix per la nova API REST. Això ens complica la transició a la versió nova i ens obliga a coordinar el llançament de la nova funcionalitat amb les unitats que tinguin instàncies de mailtoticket.

Si resulta que algú el repo amb els canvis de master, correm el risc que li deixi de funcionar si encara no ha configurat el nou servei.

Sent més conservador, jo hauria mantingut el suport de SOA i en tot cas afegit el suport per la nova API REST i que cadascú pogués triar en quin moment migrar via canvi configuració de la instància. Què en penseu?

En cas contrari, com penseu que hem de fer el llançament de la versió amb aquesta característica?

**Comment by aaguilera** [comment]
Jo penso diferent: prefereixo que em deixi de funcionar en el moment que actualitzo (perquè és quan m'adonaré que ha canviat alguna cosa i em posaré a mirar el README -on haurem d'explicar el canvi-, fer un `git log`, etc). En l'altre cas, actualitzaria, tot seguiria funcionant, i hi hauria un moment en que deixarà de funcionar i no sabria com és que falla "si jo avui no he tocat res".

Sigui com sigui, crec que és un bon moment per començar a fer servir releases i nombres de versió. Jo ara faria una release 1.x.y (per exemple) de la branca master actual, i després en faria una altra 2.0.0, un cop integrada la branca amb la nova API de gestió d'identitat.

Per altra banda, crec que hi ha una llista d'usuaris de mailtoticket (encara existeix?), i podem fer-la servir per avisar els usuaris del canvi (tot i que potser no hi són tots, és clar) i que estiguin preparats.

**Comment by jaumemoral** [comment]
Jo també crec que millor fer el canvi fent que lo antic deixi de funcionar, amb la idea de "si t'actualitzes a aquesta versió, es per fer-ho amb la API REST". Sense compatibilitat cap enrera bàsicament perque... la idea es precisament que el SOA es donarà de baixa en breu.

Em sembla perfecte per 2 releases, una amb el master actual i una despres d'aprovar el canvi (en quan l'hagueu provat algu mes a part de mi, que no tinc exactament el mateix codi)

**Comment by alexm** [comment]
> Jo penso diferent: prefereixo que em deixi de funcionar en el moment que actualitzo (perquè és quan m'adonaré que ha canviat alguna cosa i em posaré a mirar el README -on haurem d'explicar el canvi-, fer un `git log`, etc). En l'altre cas, actualitzaria, tot seguiria funcionant, i hi hauria un moment en que deixarà de funcionar i no sabria com és que falla "si jo avui no he tocat res".

La meva experiència és que segons com tinguis configurat el mailtoticket pot passar força temps (mesos) fins que t'adones que el Servei d'Identitat ja no funciona.

En general trobo que és una mala experiència com a usuari si un programa deixa de funcionar després d'una actualització sense cap avís previ i que el canvi estigui documentat no ho fa millor.

> Sigui com sigui, crec que és un bon moment per començar a fer servir releases i nombres de versió. Jo ara faria una release 1.x.y (per exemple) de la branca master actual, i després en faria una altra 2.0.0, un cop integrada la branca amb la nova API de gestió d'identitat.

D'acord.

> Per altra banda, crec que hi ha una llista d'usuaris de mailtoticket (encara existeix?), i podem fer-la servir per avisar els usuaris del canvi (tot i que potser no hi són tots, és clar) i que estiguin preparats.

Tot just aquest cap de setmana han tancat la llista per falta d'activitat. Voleu que la rescatem o busquem una altra via per informar?

**Comment by iolandagarcia** [comment]
Hola, responc a dos preguntes que heu fet i que sincerament he vist mentre llegia en diagonal ;)
- La vella Gid deixarà d'estar operativa quan la nova es consideri en PRO al 100%, esperem a l'octubre. Fins llavors coexisteixen ambdós sistemes, però la nova a vegades pateix talls de servei i resets de dades, per tant encara no està al 100%.
- En quant a la comunicació del canvi, em consten les següents instàncies del mailtotiket: UTG CNTIC (Jaume Moral), ETSECCPB (Àngel Aguilera), UTG CBL (Carlos Loscos, pendent contactar), UPCnet (Albert Solana, pendent contactar) i EPSEVG (Ruben Menendez, no l'han arribat a fer servir mai).
Si vosaltres teniu constància que hi hagi més instàncies, si us plau, meu-m'ho saber. A vegades no es fan subscripcions pq es re-usen usuaris SOA o APIKeys d'altres sistemes d'informació.
Gràcies.

**Comment by alexm** [comment]
@iolandagarcia al DAC (ara UTG CNTIC) també tenen una instància de mailtoticket (el contacte era jo abans de traslladar-me) però ens va caducar l'accés al Servei d'Identitat fa temps i no vam tornar-lo a tramitar.

**Comment by iolandagarcia** [comment]
@alexm llavors entenc que el del DAC no el fan servir. En tot cas ara tenen el de la UTG. Cert ? Vull dir, que no he de generar cap APIKey  ni perseguir a ningú pq s'adaptin ;)

**Comment by alexm** [comment]
@iolandagarcia al DAC ara no fan servir la cerca d'adreces al Servei d'Identitat (tot i que vam comentar diversos cops que seria interessant perquè sinó tots els tiquets que no vinguin d'adreces upc.edu s'assignen per defecte a l'usuari genèric del DAC).

**Comment by jlopezramos** [comment]
Hola a tots,
soc Jose López, del campus de Castelldefels (UTG CBL).
Hem actualitzat fa uns dies de forma manual la nostra instància amb el que ha posat @jaumemoral a la branca "feature_api_rest_identitat" (moltes gràcies!)
No obstant, ens funciona correctament excepte en un cas (no sé si hi ha més, estem fent proves). Amb un correu d'ATIC, quan intenta obtenir la UID del solicitant, obté "upclink.test" (¿?). Aquest és un usuari que no té permisos per crear tiquets al nostre domini i no funciona. Exactament amb el mateix correu, fent servir la instància anterior (via SOA), el UID és "atic" (correcte) i es crea perfectament el tiquet.
Fent servir qualsevol altre remitent ens funciona correctament, al menys fins on hem provat. Heu tingut algun problema similar? Alguna idea del que pot passar?
Salutacions i gràcies.

**Comment by jaumemoral** [comment]
Amb quin mail exactament et dona problemes? De vegades pot haver-hi diferents usuaris que tenen el mateix mail i llavors per codi s'intenta buscar quin es el millor usuari...

**Comment by jlopezramos** [comment]
No ho havia posat per no generar possible spam. És amb atic arroba upc.edu.
Pensava que fer servir el mateix codi (get_uid) s'obtendria el mateix resultat en tots dos entorns, però sembla que no. 
He preguntat per correu també a la @iolandagarcia, per si hi ha algun canvi a la part d'Identitat Digital.
Moltes gràcies!

**Comment by jaumemoral** [comment]
Ep, crec que veig per on van els tiros. Jo a la meva instalació vaig passar a utilitzar identitats en comptes de persones per un tema d'un mail genèric que no trobava. De fet... encara no se exactament quina es la diferència entre persones i identitats

Prova a canviar aquestes linies del identitat.py

```
  if "@upc.edu" in mail:
                cn = mail.split("@")[0]
                try:
                    cn = mail.split("@")[0]
                    persona = requests.get(
                        self.url+"/externs/persones/"+cn+"/cn",
                        headers={'TOKEN': self.token}).json()
                    return persona['commonName']
                except Exception:
                    None
```

per aquestes

```
 if "@upc.edu" in mail:
              try:
                cn = mail.split("@")[0]
                dades_persona=requests.get(self.url+"/externs/identitats?cn="+cn,
                               headers={'TOKEN':self.token}).json()
                return cn
              except:
                None
```

**Comment by jlopezramos** [comment]
Funciona! però... per a què serveix la part de dades_persona=.... si fem direcament un "return cn" retornant el que hi ha davant de l'@?

**Comment by jaumemoral** [comment]
mmmm, doncs ara que ho veig... per res. Realment el que faig es buscar si existeix algu amb el cn corresponent. Si no existeix, petarà (torna un 404) i si va be ja pot retornar el cn que ha buscat, no cal ni saber que hi ha a les dades, només saber que existeix.

Suposo que al seu moment vaig provar a fer alguna comprovació addicional, pero realment no cal

**Comment by jlopezramos** [comment]
Perfecte doncs! El deixo tal qual de moment. Sigui com sigui, molt agraït per l'ajuda!
Salutacions,
