### ISSUE TITLE
Forçar la versio de python pel Travis

### ISSUE THREAD

**Issue by jaumemoral** [UPC/mailtoticket#189]
Actualment a Travis no li diem si fem servir Python 2 o 3. Pel que he vist, ara mateix si fem una nova branca, intenta passar els testos amb Python 3 i peta.

Estaria bé fer un canvi al fitxer de Travis per dir que vlem Python 2.7 i un cop fet aixo, posar-nos amb la issue de passar a Python 3 (#187) de forma civilitzada, no perque el Travis decideixi unilateralmemnt que utilitza la última versió

**Comment by jaumemoral** [comment]
He fet una PR #190 a veure si ara construeix correctament.

**Comment by jaumemoral** [comment]
Sembla que si que ho fa correcte. Us sembla be acceptar-la? Aixi en qualsevol canvi que fem a partir d'ara es passaran els testos correctament.

**Comment by alexm** [comment]
Ja he aprovat els canvis al #190. Endavant amb la integració.
