### ISSUE TITLE
Actualitzar la configuració del repositori pel que fa als builds del Travis

### ISSUE THREAD

**Issue by aaguilera** [UPC/mailtoticket#216]
He vist que hi ha alguns PR que estan pendents d'executar els checks del Travis. Mentre mirava què podia estar passant, he vist que al web de Travis hi ha [un avís](https://travis-ci.org/github/UPC/mailtoticket) indicant que, des del 15 de juny, els builds contra travis-ci.org estan deshabilitats, i que s'han de fer contra travis-ci.com.

Cal configurar el repo de MailToTicket per tal que els builds es facin contra travis-ci.com, i veure quines implicacions té això si han canviat les condicions d'ús, etc.

**Comment by aaguilera** [comment]
He fet la migració del repo a travis-ci.com. He configurat el pla gratuït.
He vist que hi ha configurat un _webhook_ que encara apunta a travis-ci.org: https://github.com/UPC/mailtoticket/settings/hooks/78641794 (sembla que encara funciona, ja que fa una redirecció automàtica)

**Comment by aaguilera** [comment]
A la configuració del repo, a l'apartat [Branches](https://github.com/UPC/mailtoticket/settings/branch_protection_rules/78158), he hagut de desactivar la regla **continuous-integration/travis** (que sembla que ja no s'executa mai) i he afegit les regles **Travis CI - Branch** i **Travis CI - Pull Request**. Amb això sembla que els checks dels PR tornen a executar-se correctament.

**Comment by aaguilera** [comment]
En una branca he vist que els checks del Travis no s'executaven automàticament, i la branca ni tan sols apareixia a la web del Travis. Ho he resolt amb un commit "buit" en aquella branca. Per exemple:

    commit -m "Commit buit per notificar al Travis" --allow-empty

Fent això la branca ja apareix a la web del Travis, i els checks s'executen.

**Comment by alexm** [comment]
Moltes gràcies per configurar de nou el Travis, @aaguilera. Falta alguna cosa més per resoldre aquest tiquet?

**Comment by aaguilera** [comment]
No, Jo crec que ja es podria tancar.
