### ISSUE TITLE
Fer que els reply només es facin si coneixem el mail de qui l'envia

### ISSUE THREAD

**Issue by jaumemoral** [UPC/mailtoticket#22]
Aixo vol dir o que es un mail conegut o bé que coincideix amb el mail amb el qual s'ha creat el ticket i que ara ja podem consultar a la api v6

https://genwebv4.upc.edu/soa/ca/contractes-soa/MANUALUSUARIServeisWebGIDPersonesv6.pdf

**Comment by jaumemoral** [comment]
El tema es... val la pena? Ara mateix el comportament es que si es un reply i no detecto el mail, poso un comentari com si fos el solicitant. I em costa veure un cas on aixo no sigui vàlid

**Comment by alexm** [comment]
Entenc que si al comentari del principi del tiquet que posa el mailtoticket ja té la informació de qui ha enviat el correu hauria de ser suficient utilitzar l'usuari genèric per afegir el comentari, oi?

Assumir que és un comentari del sol·licitant és una opció però aleshores perdem la informació del fet que no hem sabut associar-li aquesta adreça.

Una altra opció seria indicar aquest fet a la línia del principi també i afegir el comentari com el sol·licitant, però crec que m'agrada més l'opció de fer-ho amb l'usuari genèric.

**Comment by alexm** [comment]
En qualsevol cas, crec que el comentari s'hauria d'afegir sempre.

**Comment by jaumemoral** [comment]
Aixo ja està fet i a sobre encara tenim una pull request per acabar de pulir el tema de les notificacions.

https://github.com/UPC/mailtoticket/pull/129

Tanco!
