### ISSUE TITLE
Attachements

### ISSUE THREAD

**Issue by nuriarc02** [UPC/mailtoticket#25]
He fet avui una prova amb un e-mail que portava incrustada una imatge, no ha posat la imatge al comentari sino que l'ha posat con annexe. Ja em va bé, però potser en aquest cas i quan s'annexe un fitxer seria bo afegir una línia en el comentari indicant-lo.

**Comment by jaumemoral** [comment]
De fet, com que l'attachment queda amb una URL concreta, seria possible posar un tag amb la imatge. M'hauria de mirar bé com fer la substitució per no liar-la.

**Comment by jaumemoral** [comment]
Pel que volia fer necessito que quan afegeixo un annex a un ticket el servei SOA em digui el ID amb que s'ha creat, aixi després puc fer la substitució dintre del cos del ticket.

He obert petició a eATIC a veure si em fan cas... De fet quan dones d'alta un ticket ja funciona aixi, pero quan es un attachment no.

Deixo aqui la petició feta:
https://gn6.upc.edu/atic/control/aticTiquetDetallDadesGenerals?requirementId=610045

**Comment by jaumemoral** [comment]
La idea al final es fer un "replace" de les URL d'images del tipus

<img src="cid:part1.06010904.01020400@fib.upc.edu">

Per l'attachment corresponent al cid de la URL

--------------030003010309010403090301
Content-Type: image/png;
 name="iaabddeg.png"
Content-Disposition: inline;
 filename="iaabddeg.png"
Content-ID: <part1.06010904.01020400@fib.upc.edu>
Content-Transfer-Encoding: base64

**Comment by jaumemoral** [comment]
Tenim resposta:
----
tenim el vistiplau per incorporar al servei web "GestioTiquets" un nou camp amb el Id del annex per l'operació d'annexar a tiquet .

Aquesta modificació estarà disponible en les properes versions de GN6. No serem a temps però de incloure-la en la versió que lliurarem aquesta setmana.
----

Aixi doncs, aviat ens hi podrem posar

**Comment by jaumemoral** [comment]
Sembla que ja podem continuar.

Proposo canviar la funcio

 self.afegir_attachments(self.ticket_id,self.solicitant)

Per

body=self.afegir_attachments_actualitzant_body(self.ticket_id,self.solicitant,body)

**Comment by jaumemoral** [comment]
Fet! A l'ultima versió ja està disponible
