### ISSUE TITLE
Error de format del missatge de sortida

### ISSUE THREAD

**Issue by alexm** [UPC/mailtoticket#26]
He verificat que el sendmail deixa de queixar-se quan el missatge no conté la cadena "From ..." després de la capçalera `x-mailtoticket:` però el nostre servidor imap decideix ignorar el correu igualment.

Em temo que ho fa perquè la capçalera `Message-ID:` no ha canviat i ja existeix un correu anterior que la conté, quan se suposa que és única.

Se m'acut que es podria canviar el `Message-ID` per un `In-Reply-To:` i afegir un nou `Message-ID:` com ara `{xurro aleatori, data+hora o uuid}@mailtoticket.gn6.upc.edu`.

TODO:

* [x] Inserir la capçalera `X-Mailtoticket` correctament.
* [ ] Documentar com eliminar la capçalera `Message-Id` si el servidor IMAP ho requereix.

**Comment by alexm** [comment]
La capçalera `X-Mailtoticket` s'hauria d'afegir dins del correu original, no abans, per evitar trencar el format del correu sortint.

**Comment by jaumemoral** [comment]
Ep, aixo sembla que ja està. Tanco!

https://github.com/UPC/mailtoticket/pull/118
