### ISSUE TITLE
Si el subject està en blanc, no crea el tiquet

### ISSUE THREAD

**Issue by nuriarc02** [UPC/mailtoticket#31]
Si el subject del mail està en blanc, no crea el tiquet. S'hauria de crear el tiquet amb un assumpte p.e: tiquet de X, on X és el nom del sol·licitant. 
Després el resolutor ja el modificarà si ho creu convenient.

**Comment by jaumemoral** [comment]
He fet una petita prova i a mi em surt "None", que de totes formes es molt lleig. Miro a veure si trobo el cas concret en que aixo passa

**Comment by jaumemoral** [comment]
Ja està, ara ja ho he afinat més i funciona. Ja està disponible
