### ISSUE TITLE
Notificacions amb serveis de missatgeria dels errors

### ISSUE THREAD

**Issue by alexm** [UPC/mailtoticket#35]
Enlloc de revisar els logs del mailtoticket estaria bé que pugui notificar dels errors en temps real a través d'algun servei de missatgeria o xat.

Hi ha molts serveis d'aquests així que es tractaria de fer-ho fàcil per poder afegir el plugin corresponent, no implementar suport per a tots els serveis.

**Comment by aaguilera** [comment]
Per començar, potser seria més fàcil començar per un plugin que simplement enviés un mail en cas d'error.

**Comment by alexm** [comment]
Això ja ho podríem fer amb valors diferents de la capçalera
`X-MailToTicket` i filtres de correu.
El dia 07/10/2015 9:46 a. m., "Angel Aguilera" <notifications@github.com>
va escriure:

**Comment by jaumemoral** [comment]
Actualment s'escriuen els logs al logger de python. No se si hi ha alguna
forma de que aquests logs no vagin a fitxer (o no només a fitxer)

2015-10-07 9:49 GMT+02:00 Alex Muntada <notifications@github.com>:

**Comment by jaumemoral** [comment]
He fet una primera versio configurable via settings que envia els mails per correu a l'administrador amb els logs

"notificar_errors":True,
"notificar_errors_from":"ticket-personal@est.fib.upc.edu",
"notificar_errors_to":"jaumem@fib.upc.edu",
"servidor_mail":"mail.fib.upc.edu"

**Comment by alexm** [comment]
No acabo de veure la necessitat de `notificar_errors_from` ni `servidor_mail`. Dedueixo que s'utilitzen perquè s'envia el correu amb una connexió SMTP, oi?

En aquest cas, crec que seria preferible enviar-lo a través del servidor local (típicament sendmail o equivalent) perquè si hi ha algun problema amb la xarxa es podria perdre el correu via SMTP.

**Comment by jaumemoral** [comment]
El from es per posar algo, realment es perque el mail vingui d'algun lloc que sigui configurable.

I el tema del servidor...  ho vaig connectant-me a un servidor de mail perque he vist que era la forma mes facil d'enviar un mail en python. Millor no suposar que el servidor es localhost o que tenim sendmail. Per exemple, per poder fer proves des d'un PC en windows com es el meu cas. En tot cas, els logs sempre s'escriuen.

**Comment by aaguilera** [comment]
Jaume, més amunt et preguntaves si era possible que el logger de Python enviés mails.

Veig que hi ha una classe SMTPHandler: 
https://docs.python.org/2/library/logging.handlers.html#smtphandler

Aquí hi ha un exemple de configuració: http://stackoverflow.com/a/6187851/1314986

No sé si en Python serà possible configurar l'enviament de mails només per als logs d'un cert nivell de "criticitat", a l'estil del Log4j en Java.

Per altra banda, nosaltres tenim aplicacions pròpies que envien mails fent servir el relay de la UPC. Funciona sense autenticació (enviem tant a adreces UPC com a adreces externes), però suposo que funciona perquè tenim una IP de la UPC.

**Comment by jaumemoral** [comment]
En el fons he fet algo semblant. Acumulo logs en un buffer i els envio

**Comment by alexm** [comment]
Tot i que no era exactament el que tenia en ment, els informes d'error per correu ja fan el fet d'enviar notificacions en temps real. Així doncs, crec que podem donar per resolta aquesta proposta de millora. Si més endavant hem d'afegir nous mecanismes de missatgeria ja replantejarem la idea.
