### ISSUE TITLE
Documentar el tema de la plantilla pels comentaris interns

### ISSUE THREAD

**Issue by nuriarc02** [UPC/mailtoticket#36]
Per a que això funcioni, la plantilla de 
Comentari intern de tiquet notificat, ha d'incloure a la capçalera la paraula "intern".

Ara Jaume ho té configurat així.
S'ha de tenir en compte per si d'altre gestor ho vol fer servir. S'hauria de documentar tb a la wiki

**Comment by jaumemoral** [comment]
@nuriac02, aixo ja ho hem tingut en compte a la documentacio, no? Si es aixi, ja es pot tancar

**Comment by nuriarc02** [comment]
Sí, està al document. Ho tanco
