### ISSUE TITLE
Permetre que el diccionari mails_addicionals accepti expressions regulars

### ISSUE THREAD

**Issue by alexm** [UPC/mailtoticket#37]
Això permetria que un conjunt d'adreces de correu s'associïn a un usuari concret, per exemple `^root@([a-z0-9.\-]+\.)?ac\.upc\.e(s|du)$` a l'usuari genèric del DAC.

**Comment by jaumemoral** [comment]
Segurament serà més facil d'implementar com afegint una nova propietat "patrons_mail_addicionals" amb les expressions regulars, ja que no poden funcionar com un diccionari perque s'han de provar una a una.

També he pensat que podriem permetre backreferences i aixi permetriem coses com ara...

patrons_mail_addicionals: {
   "^root@([a-z0-9.\-]+\.)?ac\.upc\.e(s|du)":"usuari.generic",
   "(.*)@upc.edu":"\1",
   "(.*)@upcnet.es":"\1"
}

Es a dir: patrons que acaben en un usuari normal o bé patrons que acaben en un usuari depenent del patró. Ara alguns d'aquests casos estan "hardcoded" i aixi seria molt més elegant

**Comment by aaguilera** [comment]
Backreferences... m'acaba d'explotar el cap :-)

El dia 22 d’octubre de 2015, 9:04, Jaume Moral <notifications@github.com>
ha escrit:

**Comment by jaumemoral** [comment]
Implementat. Falta provar-ho i millorar les expressions regulars perque sembla que no son iguals que les de perl. Igual hi ha flags de compatibilitat

**Comment by jaumemoral** [comment]
Res, malinterpretació meva. L'expressio regular es totalment valida, dono la issue per tancada.
