### ISSUE TITLE
Cal documentar els mòduls Python necessaris

### ISSUE THREAD

**Issue by aaguilera** [UPC/mailtoticket#40]
Cal documentar quins són els mòduls Python necessaris per al funcionament de MailToTicket, i com instal·lar-los.

**Comment by aaguilera** [comment]
Sense saber gaire de Python, he executat això per intentar obtenir la llista de mòduls que es fan servir actualment:

<code>
grep ^import $(find . -name "*py") | cut -f 2 -d " " | sort | uniq
</code>

**Comment by alexm** [comment]
A mi em funciona directament però potser és que ja venen els mòduls amb la
instal·lació que tenim de l'ubuntu server 14.04.
El dia 22/10/2015 13:15, "Angel Aguilera" <notifications@github.com> va
escriure:

**Comment by aaguilera** [comment]
Jo ho estic provant en una 10.04 (sí, ja sé que està fora de manteniment) :-P

**Comment by jaumemoral** [comment]
Aixi d'entrada fa servir aquests moduls i diria que son tots estandard

import email
import hashlib
import base64
import re

També fa servir el "suds" i el "mock" que incorporo amb el propi codi (aixo s'hauria de canviar, per cert, obro un ticket) i per futures versions el modul "bleach" i el "beautifulsoup4" per tema de parsing de HTML

@aaguilera, on et dona error?

**Comment by aaguilera** [comment]
L'error em dóna en executar els tests. La situació és la següent: faig un "git clone", entro al directori, executo els tests amb `python -m test.test` (sense tocar cap fitxer de configuració), i em dóna un seguit d'errors. Per exemple:

```
$ python -m test.test
EEEEEEEEEEEEEEEEEEEEEEEE
======================================================================
ERROR: test_aplicar_nou (__main__.TestAplicarFiltres)
Donat un mail nou ha de dir que aplica i que crea ticket
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/angel/src/mailtoticket/test/test.py", line 167, in test_aplicar_nou
    msg=llegir_mail("nou.txt")
  File "/home/angel/src/mailtoticket/test/test.py", line 16, in llegir_mail
    mail_ticket=MailTicket(fp)
  File "mailticket.py", line 16, in __init__
    self.filtrar_attachments_per_nom=settings.get("filtrar_attachments_per_nom")
  File "settings.py", line 13, in get
    load()
  File "settings.py", line 8, in load
    m=__import__(module,"settings")
ImportError: No module named settings_default

...
```

**Comment by aaguilera** [comment]
Ho acabo de provar a casa (Ubuntu 15.10), i em dóna els mateixos errors.

**Comment by jaumemoral** [comment]
Ep. Aixo es perque falta copiar el settings_sample a settings_default. Es
el fitxer amb les constants

**Comment by aaguilera** [comment]
Ooops! Cert. :sweat_smile:  Ara em falla només un test:
```
.......................F
======================================================================
FAIL: test_patrons_mail (__main__.TestMails)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mailtoticket/mailtoticket/test/test.py", line 206, in test_patrons_mail
    self.assertEquals("jaume.moral",uid)
AssertionError: 'jaume.moral' != None

----------------------------------------------------------------------
Ran 24 tests in 0.479s

FAILED (failures=1)
```

**Comment by jaumemoral** [comment]
Ep, prova ara!

He separat el GestorIdentitat en 2 classes, una de les quals només treballa en local. I m'he assegurat que el test agafa els settings  de l'exemple.

Amb aquestes 2 coses, els testos haurien de funcionar bé sempre. Si es aixi, tanca la issue ;)

**Comment by aaguilera** [comment]
Chachi! Tanco l'issue.
```
.......................
----------------------------------------------------------------------
Ran 23 tests in 0.294s

OK
```

**Comment by aaguilera** [comment]
Tanco l'issue.

**Comment by aaguilera** [comment]
Reobro la issue, perquè ara sí que hi ha alguns mòduls que cal documentar: bleach, unittest, discover, ...

**Comment by alexm** [comment]
La forma habitual de documentar les dependències en python és amb un fitxer [requirements.txt](https://pip.pypa.io/en/latest/user_guide/#requirements-files). En podem posar un que indiqui les dependències i les versions que cal tenir instal·lades.

Ara mateix em fallen els tests perquè el _python-bleach_ de la ubuntu 14.04 dóna errors com aquest:

```
======================================================================
ERROR: test_neteja_reply6 (test.testneteja.TestNeteja)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lcadmin/mailtoticket/test/testneteja.py", line 10, in test_neteja_reply6
    net=netejahtml.neteja(html)
  File "/home/lcadmin/mailtoticket/netejahtml.py", line 6, in neteja
    html=sanitize(html)
  File "/home/lcadmin/mailtoticket/netejahtml.py", line 26, in sanitize
    strip=True
  File "/usr/lib/python2.7/dist-packages/bleach/__init__.py", line 111, in clean
    return _render(parser.parseFragment(text))
  File "/usr/lib/python2.7/dist-packages/bleach/__init__.py", line 306, in _render
    return force_unicode(_serialize(tree))
  File "/usr/lib/python2.7/dist-packages/bleach/__init__.py", line 313, in _serialize
    stream = walker(domtree)
TypeError: 'NoneType' object is not callable
```
A l'ordinador personal em funciona bé si instal·lo la darrera versió del _bleach_ amb el _pip_.

**Comment by alexm** [comment]
L'error del [bleach](https://bugs.launchpad.net/ubuntu/+source/python-bleach/+bug/1318324) a l'ubuntu 14.04 està identificat des de fa més d'un any.

**Comment by jaumemoral** [comment]
Tanco un altre cop. He pujat el fitxer que deia l'alex amb les dependencies i he afegit ambé el suds i el mock com a modul i fora del repositori (que no hi havien de ser, pero encara no tenia clar com funcionaven aquestes coses)
