### ISSUE TITLE
Els logs apareixen barrejats quan es processen diversos correus alhora

### ISSUE THREAD

**Issue by alexm** [UPC/mailtoticket#53]
En sí mateix no és un problema però falta una marca que permeti filtrar el log i obtenir només les entrades que ens interessen. Per exemple amb en PID seria suficient.

**Comment by jaumemoral** [comment]
Igual podem aprofitar el message-id tambe per aixo?

**Comment by jaumemoral** [comment]
M'autocontesto. El pid el pot posar la llibreria de logging nomes canviant
el format. Es molt mes facil!

**Comment by alexm** [comment]
Millor el PID, és més curt i fàcil d'identificar per un humà.
