### ISSUE TITLE
Incloure el correu original als informes d'error enviats per correu 

### ISSUE THREAD

**Issue by alexm** [UPC/mailtoticket#54]
Seria de gran ajuda tenir com adjunt el correu original perquè d'aquesta manera es podria decidir com resoldre el problema i tindríem la mostra concreta que el genera, sense necessitat que el correu es guardi a l'origen.

Això seria especialment pràctic pel cas de la gestió del correu IMAP via fetchmail ja que aleshores es podria configurar el fetchmail perquè no guardi la còpia dels correus originals i quedaria tot més net.

D'altra banda, segueix havent el problema que si falla l'enviament de l'informe es perdria també el correu original tret que se n'hagi desat una còpia a l'origen.

**Comment by jaumemoral** [comment]
+1. Aniria molt be.
El dia 17/12/2015 11.40, "Alex Muntada" <notifications@github.com> va
escriure:
