### ISSUE TITLE
Netejar el bloc de la signatura PGP

### ISSUE THREAD

**Issue by jaumemoral** [UPC/mailtoticket#62]
Dintre de la funcionalitat de netejar mails, estaria bé que es "mengés" la part que hi ha entre -----BEGIN PGP PUBLIC KEY BLOCK----- i -----END PGP PUBLIC KEY BLOCK-----

**Comment by jaumemoral** [comment]
He deixat un mail de prova al repositori privat. Quan implementem, podem fer els testos amb pgp.txt

**Comment by alexm** [comment]
Ja he comentat algun cop que no hauria de ser feina del mailtoticket netejar els correus, això és cosa del gestor de tiquets. Però entenc que el GN6 és un cas molt particular perquè no ha tingut mai suport per correu i per tant d'una manera o altra l'estructura del correu original no es pot mantenir (una opció fàcil seria adjuntar el correu original al tiquet).

D'altra banda, no podem generalitzar i decidir per totes les instàncies que farem net de les determinades coses. En tot cas, hauria de ser configurable des de la instància, com un filtre més. Ho has implementat d'aquesta forma?

**Comment by jaumemoral** [comment]
@alexm, no he implementat res, simplement he recollit el mail com a joc de proves per quan implementem la neteja.

Em sembla bona idea posar el mail original com a attachment, aixi podriem fer una neteja mes agressiva.

I sobre el que dius de que sigui configurable, crec que la millor forma seria tenir tota una serie de criteris de neteja que es podrien activar o desactivar: bloc PGP, signatures, mails "quotejats", deixar només els tags html bàsics... Podriem fer-ho de forma similar a com definim actualment els filtres.
