### ISSUE TITLE
Si una persona te a identitat digital un mail diferent del estandard upc, no reconeix quan envia amb el mail upc

### ISSUE THREAD

**Issue by jaumemoral** [UPC/mailtoticket#73]
Exemple

Si l'usuari jander.clander a identitat digital te com a mail

jander@fib.upc.edu 

Llavors creo ticket com a 

jander.clander@upc.edu

No el detecta correctament

**Comment by jaumemoral** [comment]
Si posem un patro de mails que sigui el @upc.edu, solucionem el problema, pero fa que mails upc que no van a parar a cap usuari concret perque son alias no passin a buscar-se a identitat digital, d'on podriem exteure realment l'usuari

Sembla que el millor que podem fer es buscar els mails amb el següent ordre

- primer llista de mails addicionals
- llavors identitat digital
- finalment mails basat en un patró (els @upc.edu)

Si finalment el patro no es un usuari legal, el mail no es tractarà.

**Comment by alexm** [comment]
Conceptualment jo entenia que la llista de mails addicionals havia d'anar al final, no al principi. Potser hauríem de repensar aquest tema per no forçar un ordre determinat d'avaluació al codi sinó que es decideixi per configuració en quin ordre cal buscar la identitat perquè no tinc clar que tothom vulgui el mateix ordre.

**Comment by jaumemoral** [comment]
@alex, ok. Alguna idea de com ho podriem configurar sense que sigui massa complex? Potser posar una llista de gestors d'identitat i invocar-los un darrera l'altre fins que algun no retorni null? Ara mateix hi ha 2 gestors d'identitat, pero no veig problema en que n'hi hagi 3 un basat en UPC, un en llista de mails i un en patrons de mail. L'usuari pot ordenar-los com vulgui o si no, un valor per defecte que sigui la solució actual. Que et sembla?

**Comment by alexm** [comment]
Ho he de pensar una mica però estaria bé que en @jordibellido i l' @aaguilera també opinessin del tema.

**Comment by aaguilera** [comment]
Jo faig servir un framework d'autenticació/autorització que es diu "Spring Security", que permet definir diversos "AuthenticationManager", i l'ordre en que s'han de fer servir, molt semblant al que ha proposat en  @jaumemoral. A mí em sembla el camí a seguir, tenint en compte que altres van tenir la mateixa idea :-)

**Comment by aaguilera** [comment]
Ah! Sobre els detalls d'implementació, crec que tenir una llista de "gestors d'identitat" és el més simple (en Spring Security se'ls assignen prioritats, però crec que no cal complicar-se).

**Comment by alexm** [comment]
Resolt a #74.
