### ISSUE TITLE
Permetre forçar a utilitzar el mail de l'usuari per certs mails que no tenen bustia

### ISSUE THREAD

**Issue by jaumemoral** [UPC/mailtoticket#81]
Poso un exemple perque es dificil d'explicar

Suposem que tenim un mail que s'utilitza al from pero que realment no te cap bustia associada. Per exemple "reserves@fib.upc.edu". Aquest mail esta associat a un usuari concret amb un mail real i es sempre amb aquest mail amb el que s'han de crear els tickets, mai amb aquest mail virtual que realment no existeix.

Aixo es un problema que hem trobat a la FIB.

Idea d'implementació: fer una llista de mails sense bustia. Si el nostre from es un d'aquests mails sense bustia, no passarem el mail a l'hora de crear el ticket i aixi es crearà amb el mail per defecte de l'usuari.

**Comment by alexm** [comment]
Això no se soluciona amb el paràmetre `mails_addicionals` que ja tenim?

**Comment by jaumemoral** [comment]
No. La diferencia es subtil i enrevessada

Tinc una aplicacio que envia mails com a mail.fals@upc.edu a una bustia mailtoticket

**Comment by jaumemoral** [comment]
Jo poso que mail.fals@upc.edu equival a l'usuari jaume.moral... Pero no vull que el ticket es quedi amb mail.fals@upc.edu perque no existeix, sino al mail jaumem@fib.upc.edu que es el meu de veritat

**Comment by jaumemoral** [comment]
Ah. No son opcions crear un alias ni canviar el mail fals. Es un sistema desenvolupat fa temps.

**Comment by alexm** [comment]
No veig per què no hauria de ser una opció crear un àlias per molt que sigui un sistema desenvolupat fa temps.

En qualsevol cas, crec que ja tenim mecanismes suficients per fer això sense que calgui afegir canvis al codi actual mitjançant `valors_defecte`, e.g.

```
  "valors_defecte": [
    {
      "order"    : ['From'],
      "match"    : "^mail\.fals@fib\.upc\.edu$",
      "defaults" : {
        "solicitant": "nom.cognom",
        "emailSolicitant": "nom.cognom@fib.upc.edu"
      }
    }
  ]
```

**Comment by jaumemoral** [comment]
Ah, doncs es veritat! Molt ben pensat. De totes formes crec que s'ha de
tocar codi. No tinc clar que la implementacio actual matxaqui el valor del
mail

**Comment by jaumemoral** [comment]
A l'anterior hi havia un petit error, faltaven els ** al pararametres per fer el unpack del diccionari

https://github.com/UPC/mailtoticket/pull/85

Ara ja està correcte i solucionat. Tanco tot
